package main

import "fmt"

func main() {
	fmt.Println("╔══════════════════════════════════════════════════════════════════════╗")
	fmt.Println("║              Flex 布局实际渲染效果对比                                 ║")
	fmt.Println("╚══════════════════════════════════════════════════════════════════════╝")
	fmt.Println()

	fmt.Println("📺 实际渲染效果 (从 elegant_api_demo 输出):")
	fmt.Println("─────────────────────────────────────────────────────────────────────────")
	fmt.Println()
	fmt.Println("  *[ Left ]                        [ Center ]                        [ Right ]")
	fmt.Println("   ↑                              ↑                                ↑")
	fmt.Println("   ~9 字符                        ~11 字符                         ~10 字符")
	fmt.Println()

	fmt.Println("📐 预期效果 (每个按钮应该是 26 字符):")
	fmt.Println("─────────────────────────────────────────────────────────────────────────")
	fmt.Println()
	fmt.Println("  [  * [ Left ]  ]              [ Center ]              [  [ Right ] *  ]")
	fmt.Println("    ↑ 26 字符                      ↑ 26 字符                  ↑ 26 字符")
	fmt.Println()

	fmt.Println("📊 数据对比:")
	fmt.Println("─────────────────────────────────────────────────────────────────────────")
	fmt.Println()
	fmt.Println("                    预期            实际            差异")
	fmt.Println("Button 1 (Left):    26 字符        9 字符         -17 字符")
	fmt.Println("Button 2 (Center):  26 字符        11 字符        -15 字符")
	fmt.Println("Button 3 (Right):   26 字符        10 字符        -16 字符")
	fmt.Println("─────────────────────────────────────────────────────────────────────────")
	fmt.Println("Total (3×26):      78 字符        30 字符        -48 字符")
	fmt.Println()

	fmt.Println("🔍 问题分析:")
	fmt.Println("─────────────────────────────────────────────────────────────────────────")
	fmt.Println()
	fmt.Println("✅ Measure 阶段: 正确")
	fmt.Println("   - HStack.MeasureLayout 返回 flexWidth=26")
	fmt.Println("   - Button.Measure(26, 26) 返回 Width=26")
	fmt.Println()
	fmt.Println("✅ Layout 阶段: 正确")
	fmt.Println("   - SetBounds(0, 3, 26, 1) 被调用")
	fmt.Println("   - bounds[2] = 26 (正确)")
	fmt.Println()
	fmt.Println("❌ Paint 阶段: 异常")
	fmt.Println("   - 按钮显示为自然宽度 (9-11 字符)")
	fmt.Println("   - 说明 Paint() 没有使用 bounds[2]")
	fmt.Println()
	fmt.Println("🎯 根本原因:")
	fmt.Println("─────────────────────────────────────────────────────────────────────────")
	fmt.Println()
	fmt.Println("**Button.Paint() 的 b.bounds[2] = 0**")
	fmt.Println()
	fmt.Println("可能的原因:")
	fmt.Println("1. Paint() 在 SetBounds() 之前被调用")
	fmt.Println("2. 存在多个 Button 实例，Paint 的实例不是 SetBounds 的实例")
	fmt.Println("3. VNode diff/reuse 导致 Paint 使用了旧的实例")
	fmt.Println()

	fmt.Println("💡 验证方法:")
	fmt.Println("─────────────────────────────────────────────────────────────────────────")
	fmt.Println()
	fmt.Println("在 Button.Paint() 开始处添加日志:")
	fmt.Println()
	fmt.Println(`  fmt.Printf("[Paint] label=%q, bounds=%v, x=%d, y=%d\n", b.label, b.bounds, x, y)`)
	fmt.Println()
	fmt.Println("运行 demo 并查看输出:")
	fmt.Println()
	fmt.Println("  $ ./elegant_api_demo.exe 2>&1 | grep '\\[Paint\\]'")
	fmt.Println()
	fmt.Println("期望看到:")
	fmt.Println("  [Paint] label='Left', bounds=[0, 3, 26, 1], x=0, y=3")
	fmt.Println()
	fmt.Println("如果看到:")
	fmt.Println("  [Paint] label='Left', bounds=[0, 0, 0, 0], x=0, y=3  ← bounds 全是 0!")
	fmt.Println("  那就证实了 Paint 在 SetBounds 之前被调用")
	fmt.Println()

	fmt.Println("🔧 解决方案:")
	fmt.Println("─────────────────────────────────────────────────────────────────────────")
	fmt.Println()
	fmt.Println("方案 1: 修复调用时序")
	fmt.Println("  确保渲染流程: Layout → SetBounds → Paint")
	fmt.Println()
	fmt.Println("方案 2: 修改 Button.Paint()")
	fmt.Println("  使用传入的 x, y 参数和计算的 width，而不依赖 bounds")
	fmt.Println()
	fmt.Println("方案 3: 在 Measure 阶段缓存 layoutWidth")
	fmt.Println("  Button 记住自己的 constrained width，Paint 时使用它")
	fmt.Println()
}
